version: '3.8'

services:
  mysql:
    container_name: spring_batch
    image: mysql:8.0
    platform: linux/amd64
    restart: on-failure
    environment:
      MYSQL_DATABASE: spring_batch
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
