version: '3.8'

services:
  mysql:
    container_name: spring_batch
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: spring_batch
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_CHARSET: utf8mb4
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
