spring:
  batch:
    job:
      names: ${job.name:NONE} # Job? ??? ? Job ??? ????? ??? ?? ??
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    show-sql: true
